engines:
  rubocop:
    enabled: true
    channel: rubocop-0-48
  scss-lint:
    enabled: false
  duplication:
    enabled: true
    exclude_patterns:
    - "db/**"
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
- vendor/**/*
