language: ruby
bundler_args: --without development
rvm:
  - "1.9.3"

# The test cases are roughly split according to their test times.
# It would be better to use https://github.com/ArturT/knapsack.
env:
 - TEST_CASES="./spec/features/admin"
 - TEST_CASES="./spec/features/consumer"
 - TEST_CASES="./spec/models"
 - TEST_CASES="./spec/controllers ./spec/views"
 - TEST_CASES="./spec/requests ./spec/helpers ./spec/mailers"
 #- TEST_CASES="./spec/routing"

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.yml.example config/application.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load

script:
  - "bundle exec rspec $TEST_CASES"

notifications:
  email: false
