---

development: &test
  regions:
    - name: "Inner Melbourne"
      distributors:
      - name: "Green Grass"
      - name: "AusFarmers United"
      - name: "Blackburn FreeGrossers"
      - name: "Melb Uni Co-op"
      - name: "Edible garden"
      - name: "FruitAndVeg"
      - name: "MoreFreshStuff"

    - name: "South East Melbourne"
      distributors:
      - name: "MegaFoods"
      - name: "Eco Butchers"
      - name: "Eastern Wines"
      - name: "QuickFresh"

    - name: "Mildura"
      distributors:
      - name: "Fooderers"
      - name: "Food Local"

    - name: "South East Gippsland"
      distributors:
      - name: "Green Food Trading Corporation"
      - name: "Better Food"
      - name: "Gippsland Poultry"

test:
  <<: *test

staging:
  regions:
    - name: "Inner Melbourne"
      distributors:
      - name: "Eaterprises (Ballantyne)"
      - name: "PepperTree Place"
      - name: "Childcare Center"
      - name: "Bulk Foods Coop"
      - name: "Sporting Club"

    - name: "South East Melbourne"
      distributors:
      - name: "South East Food Hub"
      - name: "Primary School"
      - name: "Farmers Market"
      - name: "Neighbourhood Coop"

    - name: "Regional Victoria"
      distributors:
      - name: "SW Food Hub"
      - name: "Farmer Coop"
      - name: "Mildura Food Centre"
      - name: "Grow Lightly (Korumburra)"


production:
  regions:
    - name: "Eaterprises"
      distributors:
      - name: "Murundaka (Heidelberg)"
      - name: "Ballantyne (Thornbury)"
      - name: "O'Hea Street, Coburg"
