developement:
  bucket: openfoodweb_test
  access_key_id: AKIAJ3EE2EKGP36D4PUA
  secret_access_key: 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
production:
  bucket: openfoodweb_production
  access_key_id: AKIAJ3EE2EKGP36D4PUA
  secret_access_key: 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